### PR TITLE
4.4.0-0.0.1: [fix]: Default Export

### LINKED ISSUE #195: Getting Started sample failing on Node 14.8
Hello!

Trying to setup the sample on Node 14.8 locally provides the following error:

```
const blocknative = new BlocknativeSdk(options)
                    ^

TypeError: BlocknativeSdk is not a constructor
```

Complete code snippet:
```
import WebSocket from 'ws'
import BlocknativeSdk from 'bnc-sdk'
import Web3 from 'web3'

// const web3 = new Web3('<ws://some.local-or-remote.node:8546>')

// create options object
const options = {
  dappId: '<API>',
  networkId: 4,
  ws: WebSocket,
  // un-comment if you would like to log all transaction events
  transactionHandlers: [event => console.log(event.transaction)]
}

// initialize and connect to the api
const blocknative = new BlocknativeSdk(options)
```

Running via `node index.js`

Local information:
- node version == v14.18.0
- package.json type == module

### PR DESCRIPTION
**Pull request by aaronbarnardsound**
### Description
The previous release introduced a bug when importing the default SDK package due to mixed named and default exports. This PR makes changes so that only a default export is used and the multichain SDK is now included as a static method on the regular SDK.

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] I tested locally to make sure this feature/fix works

Fixes #195

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,5 +1,290 @@
...
+      this._socket.close()
+      this._destroyed = true
+
+      // call onclose manually here as SturdyWebSocket doesn't currently work as expected
+      // https://github.com/dphilipson/sturdy-websocket/issues/5
+      this._socket.onclose()
+    }
+  }
+
+  static multichain(options: MultiChainOptions) {
```
Comment (Adamj1232) [inline src/index.ts:180]: 💯

File: README.md [hunk 2]
```diff
@@ -175,9 +175,9 @@ For apps that operate on multiple chains at once, you can use the Multichain SDK
 Currently a transaction hash or account address can be subscribed to for all events. The `subscribe` method requires an `id`, `chainId` and a `type` and returns an `Observable`. The `Observable` that is returned is specific for events on this subscription and on completion or unsubscribing from the observable will automatically unsubscribe within the SDK. Alternatively you can listen on the global transactions `Observable` at `sdk.transactions$`.
 
 ```javascript
-import { MultichainSDK } from 'bnc-sdk'
+import Blocknative from 'bnc-sdk'
 
-const blocknative = new MultichainSDK({ apiKey: '<YOUR_API_KEY>' })
+const blocknative = Blocknative.multichain({ apiKey: '<YOUR_API_KEY>' })
```
Comment (Adamj1232) [inline README.md:180]: 💪

**Review by Adamj1232 — APPROVED** [review]
Looks good! I havent used JS classes since my days full stacking on a Java team, love to hate and hate to love. Nice work!
